### ISSUE TITLE
Error: Call to undefined function Freshbitsweb\LaravelCartManager\Core\money_format()

### ISSUE THREAD

**Issue by caophihung94** [freshbitsweb/laravel-cart-manager-demo#1]
![2018-06-15_134938](https://user-images.githubusercontent.com/15188241/41454334-35d280ce-70a3-11e8-939c-2abdf7617913.PNG)

**Comment by gauravmak** [comment]
Hi @caophihung94, Which version of PHP are you using? I couldn't reproduce the issue.

**Comment by caophihung94** [comment]
Hi @gauravmak , I'm using PHP 7.2.5

**Comment by gauravmak** [comment]
Just found that `money_format()` isn't supported in Windows. https://stackoverflow.com/a/21508027/3113599

Have to create a custom function to support. We may consider working on it. You may create a pull request anytime. Thanks.
